name: KataRuntime Plugin CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
    - name: Build the in Docker
      run: |
        chmod +x ./build_in_docker.sh
        chmod +x ./source/pkg_build.sh
        ./build_in_docker.sh
